# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os .environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_Caesar(object):
    def setupUi(self, Caesar):
        Caesar.setObjectName("Caesar")
        Caesar.resize(796, 717)
        font = QtGui.QFont()
        font.setPointSize(20)
        Caesar.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Caesar)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 231, 51))
        self.label.setMinimumSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 360, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 570, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(140, 130, 601, 121))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 290, 601, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 360, 601, 161))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 570, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        Caesar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Caesar)
        self.statusbar.setObjectName("statusbar")
        Caesar.setStatusBar(self.statusbar)

        self.retranslateUi(Caesar)
        QtCore.QMetaObject.connectSlotsByName(Caesar)

    def retranslateUi(self, Caesar):
        _translate = QtCore.QCoreApplication.translate
        Caesar.setWindowTitle(_translate("Caesar", "MainWindow"))
        self.label.setText(_translate("Caesar", "CAESAR CIPHER"))
        self.label_2.setText(_translate("Caesar", "Plain Text:"))
        self.label_3.setText(_translate("Caesar", "Key:"))
        self.label_4.setText(_translate("Caesar", "Cipher Key:"))
        self.pushButton.setText(_translate("Caesar", "Encrypt"))
        self.pushButton_2.setText(_translate("Caesar", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Caesar = QtWidgets.QMainWindow()
    ui = Ui_Caesar()
    ui.setupUi(Caesar)
    Caesar.show()
    sys.exit(app.exec_())
